"""Initial migration

Revision ID: 0d0104003610
Revises: 
Create Date: 2025-03-26 12:07:59.382990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0104003610'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_category')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('tweet_text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('tweet_text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('position')

    op.create_table('_alembic_tmp_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
